### ISSUE TITLE
Event Listener for Clear

### ISSUE THREAD

**Issue by chicagocomputerclasses** [viclafouch/mui-file-input#10]
How can we assign an event when the little (x) clear button is pressed to clear the file input?

I suppose we can just useEffect and react when file input changes, but it would be nice to have a cleaner way like
`<MuiFileInput onClear={  () => {} } /> `

**Comment by viclafouch** [comment]
Hello @chicagocomputerclasses !

What about this ?

```tsx
  const handleChange = (newValue: File[]) => {
    if (newValue.length === 0) {
      // clear ?
    }
  }
```
