### ISSUE TITLE
How to use multiple file upload with TypeScript and ReactHookForm?

### ISSUE THREAD

**Issue by ryub3n** [viclafouch/mui-file-input#14]
How to use multiple file uploads with TypeScript and ReactHookForm?

The CodeSandbox on the react-hook-form page doesn't work
https://codesandbox.io/s/react-hook-form-with-mui-file-input-llrkce?fontsize=14&hidenavigation=1&theme=dark

**Comment by viclafouch** [comment]
Fixed
