### ISSUE TITLE
Cannot change the placeholder font color

### ISSUE THREAD

**Issue by eide-1** [viclafouch/mui-file-input#16]
**Describe the bug**
The default shade of grey used for placeholder text on the MuiFileInput component does not meet the W3C minimum contrast requirement. I tried changing the color of the placeholder text using the `sx` property, but it does not seem to work. I can easily change the font size using this method, but the color stays the same.

Code used to change font size (this works):
```
<MuiFileInput
    multiple
    placeholder="Click here and select file(s)"
    value={selectedFiles}
    onChange={handleChange}
    hideSizeText
    sx={{
        '& .MuiFileInput-placeholder': {
            fontSize: 20
        },
    }}
/>
```
Code used to change font color (this does NOT work):
```
<MuiFileInput
    multiple
    placeholder="Click here and select file(s)"
    value={selectedFiles}
    onChange={handleChange}
    hideSizeText
    sx={{
        '& .MuiFileInput-placeholder': {
            color: 'black'
        },
    }}
/>
```
**Expected behavior**
I should be able to change the color of the placeholder text using `sx`

**Comment by viclafouch** [comment]
Hello ! 

Please share a sandbox in order for me to test that

**Comment by eide-1** [comment]
Hello, 

Thank you for your prompt response. Please take a look at the code sandbox I just created. I can easily change the font size of the placeholder text, but I cannot seem to change the color: [Demo App - Codesandbox](https://codesandbox.io/p/sandbox/vibrant-noyce-jx3fpi?file=%2Fapp%2Fpage.tsx%3A2%2C35).

Thanks!

**Comment by lucasstine-demandiq** [comment]
I got this to work changing 
`
sx={{
        "& .MuiFileInput-placeholder": {
          color: "black",
        },
      }}`
to
`sx={{
        "& span.MuiFileInput-placeholder": {
          color: "black",
        },
      }}`

**Comment by lucasstine-demandiq** [comment]
You can get around this with ` color: "black !important"` but this will make the whole sx object to override everything defined there.

**Comment by eide-1** [comment]
> You can get around this with ` color: "black !important"` but this will make the whole sx object to override everything defined there.

Thank you! The suggested fix worked flawlessly.
