### ISSUE TITLE
Parameter to change the number of character before trunking of file name.

### ISSUE THREAD

**Issue by VincentBe** [viclafouch/mui-file-input#21]
Hi,

I have a problem with the file name displayed in the control. It's limited to a certain fixed number of characters. In my case, I expand the control with the "fullWidth" parameter. The border and the size part are correctly expanded along the form but the file name still trunked with about 18 characters "filename_...xyz.uvw" (leaving much of the control empty).

I found in the code that this text is trunked at 20. Is it possible to change this fixed value to a parameter? Then we can choose it in the view (with a default value of 20).

I think, it's not the best solution because of font behavior (non monospaced typefaces) but a easy to implement solution.

Regards,

Vincent

**Comment by viclafouch** [comment]
Hello ! 

COuld you share a codesandbox plz ?

**Comment by yuya-tani** [comment]
Hi.

I have the same issue, how did you solve this?
I would appreciate it if you could tell me how to do it.

Best regard.

ver. 2.0.4

![image](https://github.com/viclafouch/mui-file-input/assets/22019718/b6dbd41a-2128-4655-917f-f5dc0c7dd843)

I think it's probably here, but I would appreciate it if you could pass this as a parameter.

![image](https://github.com/viclafouch/mui-file-input/assets/22019718/5ebe15ad-f1bf-4f20-b814-208e179a8bf9)

**Comment by viclafouch** [comment]
Hey i

It has been fixed in 2.0.6 ! There is no truncate in JS anymore, CSS handles it now

**Comment by yuya-tani** [comment]
Hi.
Thanks for your quick response.
I tried updating to the latest and got the best results.
This library is great and easy to use.

thankful to you!

**Comment by VincentBe** [comment]
Hi,

Sorry I don't have a lot of time for the moment. I will try after my holidays.

Thanks.

Vincent
