### ISSUE TITLE
File accept type setting

### ISSUE THREAD

**Issue by crlosif** [viclafouch/mui-file-input#26]
Thank you for this module.

I think File input have to get functions for setting file acceptable type
But I didn't find this functions

Thank you

**Comment by viclafouch** [comment]
I'm not sure, 

```ts
 <MuiFileInput
        placeholder="Choose a file"
        inputProps={{
          accept: 'video/*'
        }}
        multiple
        value={value}
        onChange={handleChange}
        label="test"
      />
```

is what you looking for ?

**Comment by crlosif** [comment]
Thank you

I couldn't find it in documentation
