### ISSUE TITLE
Name each file for multiple files

### ISSUE THREAD

**Issue by Judimax** [viclafouch/mui-file-input#3]
**Is your feature request related to a problem? Please describe.**
right now I just see x  files when multiple files are uploaded  I want the names of each files so the user can pick and choose which files to remove from the list

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by viclafouch** [comment]
Hey ! I think the current design will stay as it for `Mui-file-input`. There is no way to 'remove' a specific file.

But, on your side, you can easily create your own component for the list of files and update the current `File[]` state

**Comment by Judimax** [comment]
give me an example to do that

**Comment by viclafouch** [comment]
please*

https://codesandbox.io/s/mui-file-input-forked-tggqw7?file=/src/App.js:238-246
