### ISSUE TITLE
Warning: Prop `id` did not match. Server: ":R15aljt6jdacq:" Client: ":R4lamfkqdl9j9:"

### ISSUE THREAD

**Issue by fsmuzawar** [viclafouch/mui-file-input#30]
Hello, 

when i try to render the component using the "use client" directive, the console throws below warning.

`Warning: Prop `id` did not match. Server: ":R15aljt6jdacq:" Client: ":R4lamfkqdl9j9:"`

i am using Next JS 13.4.11 & MUI-file-input package 2.0.6
![image](https://github.com/viclafouch/mui-file-input/assets/18171896/45f4d7a2-e479-48d4-abcd-9c57ae8fd31a)

**Comment by viclafouch** [comment]
This is a bug in Next.js: https://github.com/vercel/next.js/issues/48284.

See also : https://github.com/mui/material-ui/issues/38103
