### ISSUE TITLE
Package not recognized if I install through pnpm

### ISSUE THREAD

**Issue by sankarkumar23** [viclafouch/mui-file-input#33]
I installed the package through pnpm and the component is not being recognized. Even if I add import manually `import { MuiFileInput } from 'mui-file-input'`

![image](https://github.com/viclafouch/mui-file-input/assets/12550023/cbe948be-07f3-45c5-a99d-abfd2a1aa117)

**Comment by viclafouch** [comment]
Hello ! 

Do you have a codesandbox for repro plz ?
