### ISSUE TITLE
Placeholder not rendered

### ISSUE THREAD

**Issue by bicycleghost** [viclafouch/mui-file-input#36]
The placeholder text is not showing when rendered unless a file is chose and then removed.

**To Reproduce**
1. Use MuiFileInput with a placeholder prop
2. Load the page
3. Only the clip icon is showing

Usage (with react-hook-form):
```ts
<Controller
   control={ control }
   name="profilePicture"
   render={ ({ field, fieldState }) => (
       <MuiFileInput
           label="Profile Picture"
           placeholder="Choose an image"
           { ...field }
           helperText={ fieldState.error ? "File is invalid" : "" }
           error={ !!fieldState.error }
           inputProps={{ accept: ".png, .jpg, .png, .jpeg" }}
           fullWidth
       />
   )}
/>
```

**Expected behavior**
I would expect the placeholder text to be showing at all times if no file is choose. 

**Screenshots**
![chrome_s9r0fXJ7mt](https://github.com/viclafouch/mui-file-input/assets/21306104/6b024775-df19-4490-a8ff-2187848ef098)
![chrome_pyTJQ8kdZP](https://github.com/viclafouch/mui-file-input/assets/21306104/1c532438-c597-4ca6-9c86-36a96b619631)

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome
 - Version: 116.0.5845.96

**Comment by viclafouch** [comment]
Hello ! 

Please share a codesandbox repro, without React Hook Form

**Comment by bicycleghost** [comment]
I cannot seem to reproduce the errorr in codesanbox. It seems like my setup is the problem, but I have no idea what might be causing it. The issue persists even without react-form-hook.

Also, didn't mean to close the issue (:

**Comment by bicycleghost** [comment]
I found the issue, it was because I initialized file as undefined instead of null. That seems to solve the issue.

**Comment by marcveens** [comment]
> I found the issue, it was because I initialized file as undefined instead of null. That seems to solve the issue.

This was also an issue I ran into. Shouldn't the placeholder show regardless of `file` being null or undefined?

**Comment by blinqwebstudio** [comment]
> I found the issue, it was because I initialized file as undefined instead of null. That seems to solve the issue.

I had the same thing. With the type File in the form inputs interface the only options in Typescript for the default value of the file field are File or undefined, so I put undefined and 'as a result' the placeholder was not shown before interaction with the field. 
Solution: changes the type to File | null which allowed me to put null as the default value which allowed the placeholder to be shown. Would NOT have found this without your comment!
