### ISSUE TITLE
[object File] file issue while submitting

### ISSUE THREAD

**Issue by Shivampio** [viclafouch/mui-file-input#4]
While using React hook form and then submitting the data getting **[object File]** except **File**. Replicate the exact same https://codesandbox.io/s/react-hook-form-with-mui-file-input-llrkce?fontsize=14&hidenavigation=1&theme=dark&file=/src/index.js
but still unable to resolve it in Typescript.

**Comment by viclafouch** [comment]
Hello !

I don't see any issue in the codesandbox :/

I have the correctly prompt message when submitting the form
