### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by MoFerhat** [viclafouch/mui-file-input#40]
### An error occurs in the development environment : 

![bug](https://github.com/viclafouch/mui-file-input/assets/114532343/e421bbbb-6164-4289-a580-3a43957bd55f)

This error occurs after reloading the page.
This error does not occur in version 3.0.0 and I haven't checked if the error occurs in version 3.0.1

**"mui-file-input": "^3.0.2",
"next": "^13.4.19",
"react": "18.2.0",**

EDIT : after reinstalling the "mui-file-input": "3.0.0" package, I get the same error

**Comment by baran-ozer** [comment]
![Screenshot 2023-09-22 at 13 37 32](https://github.com/viclafouch/mui-file-input/assets/61375346/078a5c2e-76d3-4c76-8325-759e818b43ab)
same here

**Comment by cwgavin** [comment]
I found the solution here:
https://github.com/viclafouch/mui-file-input/releases/tag/v3.0.0
