### ISSUE TITLE
Allow CloseButton title and aria-label props customization

### ISSUE THREAD

**Issue by bryanjtc** [viclafouch/mui-file-input#41]
**Is your feature request related to a problem? Please describe.**
I use the mui-file-input in an app that supports different languages, but i can't change the language of the close button component.

**Describe the solution you'd like**
Add props for the title and aria label

**Describe alternatives you've considered**

**Additional context**

**Comment by viclafouch** [comment]
Hello ! 

I don't know what you mean. You can pass what you want as a label, values, etc...

**Comment by bryanjtc** [comment]
I checked the source code and the only component missing the customization is the close button
```ts
           <IconButton
              aria-label="Clear"
              title="Clear"
              size="small"
              disabled={disabled}
              className="MuiFileInput-IconButton"
              onClick={handleClearAll}
            >
              <CloseIcon fontSize="small" />
            </IconButton>
```
