### ISSUE TITLE
Do Mui Icon Optional

### ISSUE THREAD

**Issue by therajuahammad** [viclafouch/mui-file-input#45]
### I used another Icon library to my project. But this library is mandatory Mui Icons. I don't want use Mui Icon library only for that and also wouldn't miss this **Awesome** FileInput Library 

`./node_modules/mui-file-input/dist/mui-file-input.es.js:4:0
Module not found: Can't resolve '@mui/icons-material/AttachFile'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./src/sections/candidates/candidate/edit/docs/upload-dialog.js
./src/sections/candidates/candidate/account-documents.js
./src/sections/candidates/candidate/candidate-view.js`

**Comment by viclafouch** [comment]
Hey ! Fixed in https://github.com/viclafouch/mui-file-input/releases/tag/v4.0.0 ! 

Ty !

**Comment by therajuahammad** [comment]
> Hey ! Fixed in https://github.com/viclafouch/mui-file-input/releases/tag/v4.0.0 !
> 
> Ty !

@viclafouch Thanks for update.
