### ISSUE TITLE
Required Issue -  Form Doesn't submit

### ISSUE THREAD

**Issue by therajuahammad** [viclafouch/mui-file-input#46]
## Form doesn't submit after file select if is it required

https://github.com/viclafouch/mui-file-input/assets/25717712/9f137d06-c1dd-4898-a4a1-c8367aed80af

`<form
        onSubmit={(event) => {
          event.preventDefault();
          console.log(value);
        }}
      >
        <MuiFileInput
          required
          placeholder="Insert a file"
          value={value}
          onChange={handleChange}
        />
        <button type="submit">Click</button>
      </form>`

**Comment by viclafouch** [comment]
Hello ! 

Could you please share the link of your codesandbox plz ?

**Comment by therajuahammad** [comment]
> Hello !
> 
> Could you please share the link of your codesandbox plz ?

Sure, Link is: https://codesandbox.io/s/mui-file-input-forked-mkv2g2?file=/src/App.js

**Comment by viclafouch** [comment]
Fixed in https://github.com/viclafouch/mui-file-input/releases/tag/v4.0.2 !

Ty !

**Comment by therajuahammad** [comment]
> Fixed in https://github.com/viclafouch/mui-file-input/releases/tag/v4.0.2 !
> 
> Ty !

@viclafouch Thanks
