### ISSUE TITLE
Pass InputAdornment props to startAdornment

### ISSUE THREAD

**Issue by alyaskana** [viclafouch/mui-file-input#49]
I am using the component and want the start icon to be clickable and also open the file picker window like input does 

I found that passing `disablePointerEvents={true}` to `InputAdornment` component should help 
https://mui.com/material-ui/api/input-adornment/#input-adornment-prop-disablePointerEvents

But I can't do it because it's hardcoded in lib:
https://github.com/viclafouch/mui-file-input/blob/f07cc45f6f09d049adeb9ff8ef4591361d69a78e/src/index.tsx#L148-L151

**Comment by viclafouch** [comment]
Hello ! 

What about a PR that wrapping the all component to make it clickable instead of only the clickable text ?
