### ISSUE TITLE
Icons are not displayed

### ISSUE THREAD

**Issue by DaliborHomola** [viclafouch/mui-file-input#50]
**Describe the bug**
Input doesn't show any icons. When I upload a file, it is hard to clear the input because the delete icon is missing.

**To Reproduce**
1. Go to [codesandbox](https://codesandbox.io/s/mui-file-input-t9epbm?fontsize=14&hidenavigation=1&theme=dark&file=/src/styles.css)
2. See missing icons before / after upload file.

**Comment by viclafouch** [comment]
Yes, that's normal. You have to show it by yourself using `InputProps`.

```js
<MuiFileInput
          sx={{ width: 300 }}
          placeholder="Choisir un fichier"
          clearIconButtonProps={{
            children: <CloseIcon fontSize="small" />
          }}
          InputProps={{
            startAdornment: <AttachFileIcon />
          }}
          required
          multiple
          value={value}
          onChange={handleChange}
          label="Your photo"
        />
```
