### ISSUE TITLE
`inputProps`, `InputProps`, `startAdornment: <AttachFileIcon />`, `accept: ".pdf"` are mixed up in 4.0.4

### ISSUE THREAD

**Issue by LikeDreamwalker** [viclafouch/mui-file-input#52]
**Describe the bug**
I'm not sure if this is a bug or if it is designed in this way, but it's really weird.
When I am trying to set the component to only accept a specific file type and also show the AttachFileIcon (not sure if it is related to a specific icon and not tested), I get stuck cause of the wrong type and prop of the component.

**To Reproduce**

1. Using 4.0.4 version
2. Use the component, which should be able to only accept a specific type of file and show the icon
From the [document](https://viclafouch.github.io/mui-file-input/docs/api-reference/#inputprops--accept), we can get a component like this to use the accept prop:
```jsx
<MuiFileInput inputProps={{ accept: 'video/*' }} />
```
And for rendering the icon, I haven't found it in the document but the source code in this [repo](https://github.com/viclafouch/mui-file-input/blob/main/docs/src/pages/index.tsx) for the main page of the document:
```jsx
        <MuiFileInput
          value={files}
          multiple
          onChange={handleChange}
          placeholder="Insert a file"
          clearIconButtonProps={{
            children: <CloseIcon fontSize="small" />
          }}
          InputProps={{
            startAdornment: <AttachFileIcon />
          }}
        />
```
And I don't know if you noticed, but actually, there are two writing styles for the `input-props`, and they both indeed can work on version 4.0.4.
When I am trying to use:
```jsx
            <MuiFileInput
              value={value}
              onChange={handleChange}
              InputProps={{
                startAdornment: <AttachFileIcon />,
                accept: ".pdf",
              }}
              placeholder="Insert a file"
              clearIconButtonProps={{
                children: <CloseIcon fontSize="small" />,
              }}
            />
```
I will get:
![image](https://github.com/viclafouch/mui-file-input/assets/45194556/19e30e9a-cec4-43b4-b3df-be29b3af1766)
back, which means that accept doesn't exist and accept is really not working.

And if I use:
```jsx
            <MuiFileInput
              value={value}
              onChange={handleChange}
              inputProps={{
                startAdornment: <AttachFileIcon />,
                accept: ".pdf",
              }}
              // inputProps={{ accept: ".pdf" }}
              placeholder="Insert a file"
              clearIconButtonProps={{
                children: <CloseIcon fontSize="small" />,
              }}
            />
```
I will get an error in console saying:
![image](https://github.com/viclafouch/mui-file-input/assets/45194556/72d09109-f1eb-4232-a22b-a1dd0b0b9a72)
And by changing `startAdornment` to ` startadornment`, it won't show the icon but can avoid browser error.

So, the finally working version for me is like:
```jsx
            <MuiFileInput
              value={value}
              onChange={handleChange}
              InputProps={{
                startAdornment: <AttachFileIcon />,
              }}
              inputProps={{ accept: ".pdf" }}
              placeholder="Insert a file"
              clearIconButtonProps={{
                children: <CloseIcon fontSize="small" />,
              }}
            />
```

**Expected behavior**
`InputProps` and `inputProps` should be merged into one prop.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge

**Additional context**
```json
{
  "name": "colossal-reader-app",
  "version": "0.1.0",
  "private": true,
  "packageManager": "pnpm@9.1.3",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@ant-design/nextjs-registry": "^1.0.0",
    "@emotion/cache": "^11.11.0",
    "@emotion/react": "^11.11.4",
    "@emotion/styled": "^11.11.5",
    "@mui/icons-material": "^5.15.19",
    "@mui/material": "^5.15.19",
    "@mui/material-nextjs": "^5.15.11",
    "@mui/system": "^5.15.15",
    "@types/ua-parser-js": "^0.7.39",
    "mui-file-input": "^4.0.4",
    "next": "14.2.3",
    "react": "^18",
    "react-dom": "^18",
    "sass": "^1.77.4",
    "ua-parser-js": "^1.0.38"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "eslint": "^8",
    "eslint-config-next": "14.2.3",
    "typescript": "^5"
  }
}

```

**Comment by viclafouch** [comment]
Hello !

It's not a bug, it comes from the [MUI TextField Documentation](https://mui.com/material-ui/react-text-field/). 

Your final version is correct. Nothing less, nothing more ;)
