### ISSUE TITLE
Implement `accept`

### ISSUE THREAD

**Issue by ghost** [viclafouch/mui-file-input#8]
**Is your feature request related to a problem? Please describe.**
I would like to filter the types of files the user can upload, e.g. `accept=".txt,text/plain"`

**Describe the solution you'd like**
Pass the `accept` prop to the file input

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/accept

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by viclafouch** [comment]
Hey !

You can achieve that by using the `inputProps` property : 

```jsx
<MuiFileInput
  placeholder="Choisir un fichier"
  inputProps={{
    accept: 'video/*'
  }}
/>
```

See here : https://viclafouch.github.io/mui-file-input/docs/api-reference/#inputprops--accept

**Comment by iliazeus** [comment]
@viclafouch can you please document it in the API reference? Multiple people (including me) thought it wasn't possible before stumbling onto this issue.

**Comment by viclafouch** [comment]
Got it !

**Comment by viclafouch** [comment]
Here the documentation : https://viclafouch.github.io/mui-file-input/docs/api-reference/#inputprops--accept
