### ISSUE TITLE
Unresponsive component width when `fullWidth` is `true`

### ISSUE THREAD

**Issue by fityannugroho** [viclafouch/mui-file-input#9]
## Describe the bug
When **`fullWidth` prop is set** (or if this component is placed inside flexbox or grid layout), the inner element (`<label>`) doesn't follow the parent width and creates an **empty space**. This empty space will be seen after the user inserts the file.

> https://user-images.githubusercontent.com/63894003/224220699-86ba6ce8-f3a8-4a1b-b879-334612ade0b9.mp4

## To Reproduce
Import and use the React component `MuiFileInput` with `fullWidth` is set, or put the `MuiFileInput` inside flexbox or grid layout.

## Expected behavior
The width of inner element will responsive to the parent elements, like this third input that named "Fixed FullWidth Input" (see picture below).

![filled input](https://user-images.githubusercontent.com/63894003/224221248-7a8466b2-eaa1-4f39-b156-1d3c49eddefd.png)

## Additional context
The **file name** also need improvement.

## Possible solution
I think by adding CSS **`width: 100%`** rule into [the `Label` styling](https://github.com/viclafouch/mui-file-input/blob/main/src/components/Input/Input.styled.ts) can solve the width issue.

But I don't know for the file name. Maybe using CSS `text-overflow` rule instead of truncate the text?

**Comment by viclafouch** [comment]
Hello @fityannugroho !

Could you please share me a codesandbox plzzzz.

**Comment by fityannugroho** [comment]
> Hello @fityannugroho !
> 
> Could you please share me a codesandbox plzzzz.

https://codesandbox.io/s/mui-file-input-jqmq7u

**Comment by fityannugroho** [comment]
> Hello @fityannugroho !
> 
> Could you please share me a codesandbox plzzzz.

Check out this @viclafouch

https://codesandbox.io/s/fixed-fullwidth-mui-file-input-jqmq7u

**Comment by dubaua** [comment]
Also want to add, that even with fixed full width, all field space should open system file dialog on click.
